exclude: '^docs/'
default_stages: [ commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]

  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ '--profile=black' ]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [ '--ignore=E501,W503' ]


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [ '--ignore=E501', '--fix' ]


  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.14.1'
    hooks:
      - id: django-upgrade
        args: [ '--target-version', '4.2' ]


  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.32.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.3'  # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        types_or: [ css, javascript ]


  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [ '--no-update' ]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
